version: "3.9"
services:
  service-absensi:
    build: ./service-absensi
    volumes:
    - .:/usr/src
    depends_on:
    - postgres
  service-monitoring:
    build: ./service-monitoring
    volumes:
    - .:/usr/src
    depends_on:
    - postgres
  service-penilaian:
    build: ./service-penilaian
    volumes:
    - .:/usr/src
    depends_on:
    - postgres
  service-logbook:
    build: ./service-logbook
    volumes:
    - .:/usr/src
    depends_on:
    - mongo
    - postgres
  frontend:
    build: ./frontend
    volumes:
    - .:/usr/src
  akun-api:
    build: ./backend
    volumes:
    - .:/usr/src
    depends_on:
    - postgres
  akun-keycloak-proxy:
    build: ./akun-keycloak-proxy
    volumes:
    - .:/usr/src
  notification:
    build: ./notification
    volumes:
    - .:/usr/src
    depends_on:
    - postgres
  nginx:
    image: nginx:1-alpine
    ports:
    - "8080:80"
    volumes:
    - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/etc/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
    - ./nginx/etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    environment:
    - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon off;']
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
    - 5432:5432
    volumes:
    - ./.tmp/var/lib/postgresql/data:/var/lib/postgresql/data
    - ./postgres-database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: proyek3
      POSTGRES_PASSWORD: proyek3
      POSTGRES_DB: proyek3
  adminer:
    image: michalhosna/adminer
    restart: always
    environment:
      ADMINER_DB: proyek3
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: proyek3
      ADMINER_SERVER: postgres
      ADMINER_USERNAME: proyek3
      ADMINER_AUTOLOGIN: 1
  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: proyek3
      MONGO_INITDB_ROOT_PASSWORD: proyek3
    volumes:
    - ./.tmp/etc/mongo:/etc/mongo
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: proyek3
      ME_CONFIG_MONGODB_ADMINPASSWORD: proyek3
    restart: unless-stopped
  redis:
    image: redis:6-alpine
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    restart: always
    environment:
      KEYCLOAK_USER: proyek3
      KEYCLOAK_PASSWORD: proyek3
      KEYCLOAK_FRONTEND_URL: http://akun.localhost:8080/keycloak-proxy/auth
      KEYCLOAK_IMPORT: /tmp/realm.json
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_USER: proyek3
      DB_PASSWORD: proyek3
      DB_DATABASE: proyek3
      DB_SCHEMA: keycloak
      PROXY_ADDRESS_FORWARDING: 'true'
    volumes:
    - ./keycloak/realm-development.json:/tmp/realm.json:ro
